steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/game-ex-be:$COMMIT_SHA"
      - "."
    id: "build"
 

  # Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/game-ex-be:$COMMIT_SHA"]
    id: "push"

  # Deploy ke Cloud Run (secret akan di-referensi ulang untuk runtime)
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "game-ex-be"
      - "--image=gcr.io/$PROJECT_ID/game-ex-be:$COMMIT_SHA"
      - "--update-secrets=KEY_CREDENTIALS=key-credentials:latest"  
      - "--set-env-vars=DB_HOST=$_DB_HOST,DB_USER=$_DB_USER,DB_PASS=$_DB_PASS,DB_NAME=$_DB_NAME,ACCESS_TOKEN_SECRET=$_ACCESS_TOKEN_SECRET,REFRESH_TOKEN_SECRET=$_REFRESH_TOKEN_SECRET"
      - "--region=us-central1"
      - "--port=5000"
      - "--timeout=1000s"
      - "--allow-unauthenticated"
      - "--platform=managed"
    id: "deploy"

  # Opsional: Hapus image lama
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "container"
      - "images"
      - "delete"
      - "gcr.io/$PROJECT_ID/game-ex-be:$COMMIT_SHA"
      - "--force-delete-tags"
      - "--quiet"
    id: "cleanup"

# Deklarasi secret yang akan diakses selama build
# availableSecrets:
#   secretManager:
#     - versionName: "projects/$PROJECT_ID/secrets/cred-KEY_CREDENTIALS_JSON/versions/latest"
#       env: "KEY_CREDENTIALS_JSON"  # Sesuaikan dengan nama secret yang benar

options:
  logging: CLOUD_LOGGING_ONLY